kafka:
  topic-name: test-topic

spring:
  kafka:
    consumer:
      bootstrap-servers: 172.30.129.33:9092,172.30.129.33:9093
      group-id: groupid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.30.129.33:9092,172.30.129.33:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:postgresql://172.30.129.33:5432/go
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
